### ISSUE TITLE
Reproduce pretrained-smollm

### ISSUE THREAD

**Issue by 01000-you** [huggingface/smollm#57]
I tried to pretrain smollm myself, but the performance was not good. However, the config has been updated recently, and the starting point of the lr schedule has changed from 500000 to 250000 iterations. Is this a valid change?

command 

```
torchrun --standalone --nnodes=1 --nproc-per-node=1  src/lighteval/__main__.py nanotron \
 --checkpoint-config-path .../checkpoints_smollm_135m/600000/config.yaml \
 --lighteval-config-path .../lighteval_config_override_template.yaml
```

lighteval_config_override_template.yaml

```
batch_size: 8
generation: null
logging:
  output_dir: "outputs"
  save_details: false
  public_run: false
  results_org: null
  tensorboard_metric_prefix: "eval"
parallelism:
  dp: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE
tasks:
  dataset_loading_processes: 8
  multichoice_continuations_start_space: null
  num_fewshot_seeds: null
  tasks: custom|arc|0|1,custom|openbook_qa|0|1,custom|winogrande|0|1,custom|commonsense_qa|0|1,custom|piqa|0|1,custom|hellaswag|0|0
  custom_tasks: .../tasks.py
```

my result

_ | params | ARC-C | ARC-E | Hellaswag | OBQA | PIQA | Winogrande | mmlu_pro | gsm8k
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
**SmolLM-ours** | 135M | 0.2466 | 0.4613 | 0.2718 | 0.298 | 0.5963 | 0.4933 | 0.1182 | _
SmolLM1-HF | 135M | 0.288 | 0.563 | 0.413 | 0.334 | 0.681 | 0.517 | 0.112 | 0.011
